
# Configuraciones
runtime: python39
service: front-card
instance_class: B2

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]

basic_scaling:
  max_instances: 2
  idle_timeout: 1m

env_variables:
  SERVER_URL: "https://service-card-irmon4e4ya-uc.a.run.app"  

# Entorno Estandar - Escala Manual 

#manual_scaling:
#  instances: 5

# Entorno Estandar - Escala Automatica 
#automatic_scaling:
#  target_cpu_utilization: 0.65
#  min_instances: 2
#  max_instances: 5
#  min_pending_latency: 30ms
#  max_pending_latency: automatic
#  max_concurrent_requests: 50
